"""category and Recipe

Revision ID: de0493319487
Revises: ffae5eead69c
Create Date: 2024-10-16 17:42:43.878209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0493319487'
down_revision = 'ffae5eead69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipies', sa.Column('title', sa.String(), nullable=False))
    op.add_column('recipies', sa.Column('description', sa.String(length=250), nullable=False))
    op.add_column('recipies', sa.Column('instructions', sa.String(), nullable=False))
    op.add_column('recipies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('recipies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('recipies', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipies', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipies', type_='foreignkey')
    op.drop_column('recipies', 'category_id')
    op.drop_column('recipies', 'updated_at')
    op.drop_column('recipies', 'created_at')
    op.drop_column('recipies', 'instructions')
    op.drop_column('recipies', 'description')
    op.drop_column('recipies', 'title')
    op.drop_table('categories')
    # ### end Alembic commands ###
